[project]
name = "power-attention"
version = "0.9.13"
description = "Kernels for symmetric-power-based linear transformers"
authors = [
  { name = "Sean Zhang", email = "sean@manifest.com" },
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  'torch>=2.5',
  'einops'
]

[build-system]
requires = [
    "setuptools==69.5.1",
    "torch>=2.5",
    "numpy>=2.2",
    "ninja==1.11.1.3",
    "pybind11==2.13.6",
    "psutil",
    "build",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.uv]
environments = [
    "sys_platform == 'linux'"
]

[project.optional-dependencies]
benchmark = [
  "flash-attn",
  "matplotlib",
  "pandas"
]

[tool.cibuildwheel]
build = "cp311-*"
build-frontend = "build[uv]"
before-all = [
    "git submodule update --init --recursive",
    "yum-config-manager --add-repo https://developer.download.nvidia.com/compute/cuda/repos/rhel7/x86_64/cuda-rhel7.repo",
    "yum clean all",
    "yum -y install cuda-toolkit-12-4",
    "ln -s /usr/local/cuda-12.4 /usr/local/cuda"
]
repair-wheel-command = "LD_LIBRARY_PATH=$(python -c 'import torch; print(torch.__path__[0])')/lib:$LD_LIBRARY_PATH auditwheel repair -w {dest_dir} {wheel}"

[tool.cibuildwheel.environment]
CUDA_HOME = "/usr/local/cuda"
PATH = '/usr/local/cuda/bin:$PATH'
LD_LIBRARY_PATH = '/usr/local/cuda/lib64:$LD_LIBRARY_PATH'
