[build-system]
requires = [
    "setuptools==69.5.1",
    "wheel",
    "torch>=2.5",
    "numpy>=2.2",
    "ninja==1.11.1.3",
    "pybind11==2.13.6",
    "build"
]
build-backend = "setuptools.build_meta"
