name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: gpu

    steps:
    - uses: actions/checkout@v4

    - name: Create virtual environment
      run: |
        python3.11 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install package with dev dependencies
      run: |
        source .venv/bin/activate
        pip install -e .[dev]

    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest perf/tests/ --junit-xml=test-results.xml

    - name: Surface failing tests
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
        title: Test results

    - name: Check benchmark results exist
      run: |
        SHA=$(git rev-parse HEAD)
        if ! ls reports/*${SHA}*.yaml 1> /dev/null 2>&1; then
          echo "::error::No benchmark results found for current commit ${SHA}."
          echo "::error::Please run 'python3 -m perf.create_report' locally before pushing."
          exit 1
        fi
